1. Create a one-dimensional array (vector) with the first 10 natural numbers and output its value.

In [78]:
import numpy as np 

a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Create a 3x3 two-dimensional array (matrix), fill it with zeros, and output its values.

In [79]:
a = np.full((3,3), 0)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Create a 5x5 array, fill it with random integers from 1 to 10, and output its value.

In [80]:
a = np.random.randint(1, 11, size=(5,5))
print(a)

[[ 7  3  2  5  7]
 [ 7  1 10  7 10]
 [ 9  4  6  2  7]
 [ 5  6  9  9  8]
 [ 8  6  1  7  4]]


4. Create a 4x4 array, fill it with random real numbers in the range 0 to 1, and output its value. 

In [81]:
a = np.random.random((4,4))
print(a)

[[0.40683176 0.74756317 0.64147    0.12893466]
 [0.61883038 0.60775258 0.95480049 0.51517318]
 [0.41282467 0.91490892 0.38202159 0.7771679 ]
 [0.05508611 0.52524741 0.41640869 0.32402305]]


5. Create two one-dimensional arrays of size 5, fill them with random integers in the range 1 to 10, and perform element-by-element addition, subtraction, and multiplication operations on them.

In [82]:
a = np.random.randint(1,11, size=(5,))
b = np.random.randint(1,11,size=(5,))
print(a)
print(b)

[ 3  9  9 10  1]
[5 5 2 5 9]


In [83]:
sum = a + b 
print(sum)

[ 8 14 11 15 10]


In [84]:
sub = a - b
print(sub)

[-2  4  7  5 -8]


In [85]:
mul = a * b
print(mul)

[15 45 18 50  9]


6. Create two vectors of size 7, fill with arbitrary numbers and find their scalar product.

In [86]:
a = np.random.randint(1, 10 , size=(7,))
print(a)

[4 7 8 1 8 9 2]


In [87]:
b = np.random.randint(1,20, size=(7,))
print(b)

[17  5  2 12 17 13  5]


In [88]:
print(np.dot(a,b))

394


7. Create two matrices of size 2x2 and 2x3, fill them with random integers between 1 and 10, and multiply them together.

In [89]:
a = np.random.randint(1, 11 , size=(2,2)) 
print(a)

[[7 5]
 [2 9]]


In [90]:
b = np.random.randint(1, 10 , size=(2,3))
print(b)

[[4 5 4]
 [3 8 7]]


In [91]:
print(np.dot(a,b))

[[43 75 63]
 [35 82 71]]


8. Create a 3x3 matrix, fill it with random integers from 1 to 10, and find its inverse.

In [92]:
a = np.random.randint(1, 11 , size=(3,3)) 
print(a)

[[ 6  2  8]
 [ 6  6 10]
 [10  8  9]]


In [93]:
print(np.linalg.inv(a))

[[ 0.1625 -0.2875  0.175 ]
 [-0.2875  0.1625  0.075 ]
 [ 0.075   0.175  -0.15  ]]


9. Create a 4x4 matrix, fill it with random real numbers between 0 and 1, and transpose it.

In [94]:
a = np.random.rand(4,4)
print(a)

[[0.1367967  0.91915344 0.87176926 0.59678528]
 [0.8476736  0.26905713 0.6073651  0.14313487]
 [0.78362486 0.43117634 0.87903965 0.13713903]
 [0.52378983 0.31561194 0.1741655  0.21864327]]


In [95]:
print(a.T)

[[0.1367967  0.8476736  0.78362486 0.52378983]
 [0.91915344 0.26905713 0.43117634 0.31561194]
 [0.87176926 0.6073651  0.87903965 0.1741655 ]
 [0.59678528 0.14313487 0.13713903 0.21864327]]


10. Create a 3x4 matrix and a 4 vector, fill them with random integers between 1 and 10, and multiply the matrix by the vector.

In [96]:
a = np.random.randint(1, 11 , size=(3,4)) 
print(a)

[[5 7 5 7]
 [4 7 9 1]
 [5 7 3 7]]


In [97]:
b = np.random.randint(1, 11 , size=4)  
print(b)

[10 10  9 10]


In [98]:
print(np.dot(a, b))

[235 201 217]


11. Create a 2x3 matrix and a 3 vector, fill them with random real numbers between 0 and 1, and multiply the matrix by the vector.

In [99]:
a = np.random.rand(2, 3)
print(a)

[[0.68327129 0.49386772 0.77541479]
 [0.31585638 0.00796266 0.89730019]]


In [100]:
b = np.random.rand(3)
print(b)

[0.11402959 0.68176563 0.91496909]


In [101]:
print(np.dot(a, b))

[1.12409575 0.86244758]


12. Create two 2x2 matrices, fill them with random integers between 1 and 10, and multiply them elementwise.

In [102]:
a = np.random.randint(1, 11, size=(2, 2))
print(a)

[[9 1]
 [1 9]]


In [103]:
b = np.random.randint(1, 11, size=(2, 2))
print(b)

[[1 6]
 [2 7]]


In [104]:
print(a*b)

[[ 9  6]
 [ 2 63]]


13. Create two 2x2 matrices, fill them with random integers from 1 to 10, and find their product.

In [105]:
a = np.random.randint(1, 11, size=(2, 2))
print(a)

[[5 9]
 [6 9]]


In [106]:
b = np.random.randint(1, 11, size=(2, 2))
print(b)

[[4 9]
 [5 4]]


In [107]:
print(np.dot(a, b))

[[65 81]
 [69 90]]


14. Create a 5x5 matrix, fill it with random integers between 1 and 100, and find the sum of the matrix elements.

In [108]:
a = np.random.randint(1, 101, size=(5, 5))
print(a)

[[17 90 13 50 40]
 [26 37 11 33 10]
 [55 48 49 79 38]
 [28 48 12 41 53]
 [20  7 44 62 36]]


In [109]:
print(a.sum())

947


15. Create two 4x4 matrices, fill them with random integers between 1 and 10, and find their difference.

In [110]:
a = np.random.randint(1, 11, size=(4, 4))
print(a)

[[ 5  3  1  4]
 [ 4  5  7  9]
 [ 1  5  6  5]
 [10  2  7 10]]


In [111]:
b = np.random.randint(1, 11, size=(4, 4))
print(b)

[[ 7  7  2  9]
 [ 7  9  9  7]
 [ 6  2  1  3]
 [ 1  6  5 10]]


In [112]:
print(a - b)

[[-2 -4 -1 -5]
 [-3 -4 -2  2]
 [-5  3  5  2]
 [ 9 -4  2  0]]


16. Create a 3x3 matrix, fill it with random real numbers in the range 0 to 1, and find a column vector containing the sum of the elements of each row of the matrix.

In [113]:
a = np.random.rand(3, 3)
print(a)


[[0.57135856 0.33639479 0.09550127]
 [0.79033759 0.10753043 0.53875399]
 [0.67152611 0.61636802 0.92516477]]


In [114]:
print(np.sum(a, axis=1))

[1.00325462 1.43662202 2.2130589 ]


17. Create a 3x4 matrix of arbitrary integers and create a matrix of the squares of those numbers.

In [115]:
a = np.random.randint(1,100, (3,4))
print(a)


[[56 63 17 43]
 [48 71 10 48]
 [ 5  4 62 47]]


In [116]:
print(np.square(a))

[[3136 3969  289 1849]
 [2304 5041  100 2304]
 [  25   16 3844 2209]]


18. Create a vector of size 4, fill it with random integers between 1 and 50, and find the square root vector of those numbers.

In [117]:
a = np.random.randint(1, 51, size=4)
np.sqrt(a)
print(a)


[ 5 22 27 16]


In [118]:
print(np.sqrt(a))

[2.23606798 4.69041576 5.19615242 4.        ]
